### ISSUE TITLE
CPAN::Meta::Validator should do stricter checks on 'filename' in 'provides'

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/CPAN-Meta#88]
Should the 'filename' key in meta-provides have a stricter check, e.g. `/\.pm$/` ?  Should scripts, .pod be rejected?

(see also https://github.com/andk/pause/issues/127)

**Comment by haarg** [comment]
What value would this add?

The spec explicitly allows using things other than modules as the filename.

**Comment by dagolden** [comment]
I agree that it should stay loose.

**Comment by Leont** [comment]
Agreed with haarg and dagolden, I don't think this is particularly useful.

**Comment by karenetheridge** [comment]
The specific case I was concerned about was people trying to get .pod files into the index, which is a bit paradoxical.

But, indeed, any file can cause a .pm to be built, via the PL_FILES feature in EUMM, so there's no real validation we can do at this level.

**Comment by dagolden** [comment]
My feeling is increasingly that I don't really care about anything other than the indexing of package names to distributions.

If someone wants to have "Foo::Bar" be lib/Foo/Bar.pod and index the Foo-Bar distribution, that's fine with me.  Maybe someone wants to have Foo::Bar just be a doc front end on some more complex thing where it's really other specific modules that get used.

Or if someone wants to ship a script and index that name instead of App::whatever, well, fine.

**Comment by haarg** [comment]
I think that using provides to index .pod files is entirely appropriate and one of the most useful things that can be done with provides.  Pod documentation should be able to be installed by name and protected by permissions just like .pm files.

**Comment by dolmen** [comment]
It is also a common practice to have `.pl` files in `lib/`. I'm using this extension for additional code that is loaded from the corresponding `.pm`. For example, I use `.pl` for generated code.

**Comment by dolmen** [comment]
Well, my practice may not be so common [according to grep.cpan.me](http://grep.cpan.me/?q=file%3A^lib%2F.*.pl%24+package).
